ElectronsMatchingBarrel:
  sample: TT
  version: Run3Winter24
  match_test_to_ref: True
  reference_object:
    object: "GenPart"
    x_arg: "pt"
    label: "Gen Electrons"
    cuts:
      event:
        #- "(({statusFlags}>>7)&1) == 1"
        - "{status} == 1"
        - "abs({pdgId}) == 11"
        - "abs({eta}) < 1.5"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    L1EG:default: "pt"
    L1EG:Iso: "pt"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency (Barrel)"
  binning:
    min: 0
    max: 100
    step: 3

ElectronsMatchingEndcap:
  sample: TT
  version: Run3Winter24
  match_test_to_ref: True
  reference_object:
    object: "GenPart"
    x_arg: "pt"
    label: "Gen Electrons"
    cuts:
      event:
        # - "(({statusFlags}>>7)&1) == 1"
        - "{status} == 1"
        - "abs({pdgId}) == 11"
        - "abs({eta}) > 1.5"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    L1EG:default: "pt"
    L1EG:Iso: "pt"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency (Endcap)"
  binning:
    min: 0
    max: 100
    step: 3
