JetTurnonBarrel_HHbbWW:
  version: Run3Winter24
  sample: HHbbWW
  match_test_to_ref: True
  reference_object:
    object: "GenJet"
    x_arg: "pt"
    label: "Gen Jets"
    cuts:
      event:
        - "abs({eta}) < 1.5"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    L1Jet:default:barrel: "pt"
    # L1Tau:default:barrel: "pt"
  thresholds: [50, 100]
  scalings:
    method: "naive"
    threshold: 0.95
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Trigger Efficiency (<threshold> GeV, barrel)"
  binning:
    min: 0
    max: 500
    step: 10

JetTurnonEndcap_HHbbWW:
  version: Run3Winter24
  sample: HHbbWW
  match_test_to_ref: True
  reference_object:
    object: "GenJet"
    x_arg: "pt"
    label: "Gen Jets"
    cuts:
      event:
        - "abs({eta}) > 1.5"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    L1Jet:default:endcap: "pt"
  thresholds: [50, 100]
  scalings:
    method: "naive"
    threshold: 0.95
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Trigger Efficiency (<threshold> GeV, endcap)"
  binning:
    min: 0
    max: 500
    step: 10

# JetTurnonEndcap_2p1_HHbbWW:
#   version: Run3Winter24
#   sample: HHbbWW
#   match_test_to_ref: True
#   reference_object:
#     object: "GenJet"
#     x_arg: "pt"
#     label: "Gen Jets"
#     cuts:
#       event:
#         - "abs({eta}) > 1.5"
#       object:
#         - "abs({eta}) < 2.1"
#   test_objects:
#     L1Jet:default:endcap: "pt"
    L1Tau:default:endcap: "pt"
#   thresholds: [50, 100]
#   scalings:
#     method: "naive"
#     threshold: 0.95
#   xlabel: "Gen. $p_T$ (GeV)"
#   ylabel: "Trigger Efficiency (<threshold> GeV, endcap)"
#   binning:
#     min: 0
#     max: 500
#     step: 10

JetTurnonForward_HHbbWW:
  version: Run3Winter24
  sample: HHbbWW
  match_test_to_ref: True
  reference_object:
    object: "GenJet"
    x_arg: "pt"
    label: "Gen Jets"
    cuts:
      event:
        - "abs({eta}) > 2.4"
      object:
        - "abs({eta}) < 5"
  test_objects:
    L1Jet:default:forward: "pt"
  thresholds: [50, 100]
  scalings:
    method: "naive"
    threshold: 0.95
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Trigger Efficiency (<threshold> GeV, forward)"
  binning:
    min: 0
    max: 500
    step: 10
