JetTrigger_Eta_Pt40To100_HHbbWW:
  sample: HHbbWW
  version: Run3Winter24
  match_test_to_ref: True
  reference_object: 
    object: "GenJet"
    x_arg: "eta"
    label: "Gen Jets"
    cuts:
      event:
        - "{pt} > 40"
        - "{pt} < 100"
      object:
        - "abs({eta}) < 5"
  test_objects:
    L1Jet:default: "eta"
    # L1Tau:default: "eta"
  thresholds: [50, 100]
  xlabel: "Gen. $\\eta$"
  ylabel: "Trigger Efficiency (<threshold> GeV, barrel) , Gen pt: 40-100 GeV"
  binning:
    min: -5
    max: 5
    step: 0.25

JetTrigger_Eta_Pt100ToInf_HHbbWW:
  sample: HHbbWW
  version: Run3Winter24
  match_test_to_ref: True
  reference_object: 
    object: "GenJet"
    x_arg: "eta"
    label: "Gen Jets"
    cuts:
      event:
        - "{pt} > 100"
      object:
        - "abs({eta}) < 5"
  test_objects:
    L1Jet:default: "eta"
    # L1Tau:default: "eta"
  thresholds: [50, 100]
  xlabel: "Gen. $\\eta$"
  ylabel: "Trigger Efficiency (<threshold> GeV, barrel) , Gen pt: >100 GeV"
  binning:
    min: -5
    max: 5
    step: 0.25
