MET_90perc:
  sample: TT
  version: Run3Winter24
  reference_object:
    object: "GenMET"
    x_arg: "pt"
    label: "Gen MET"
  test_objects:
    L1EtSum:MET: "pt"
  thresholds: [150]
  xlabel: "Gen. MET (GeV)"
  ylabel: "Trigger Efficiency (<threshold> GeV)"
  scalings:
    method: "naive"
    threshold: 0.90
  binning:
    min: 0
    max: 500
    step: 20

# MET_50perc:
#   sample: TT
#   version: Run3Winter24
#   reference_object:
#     object: "GenMet"
#     x_arg: ""
#     label: "Gen MET"
#   test_objects:
#     trackerMET:default: ""
#     puppiMET:default: "et"
#   thresholds: [150]
#   xlabel: "Gen. MET (GeV)"
#   ylabel: "Trigger Efficiency (<threshold> GeV)"
#   scalings:
#     method: "naive"
#     threshold: 0.50
#   binning:
#     min: 0
#     max: 500
#     step: 20
