TausMatchingBarrel:
  sample: TT
  version: Run3Winter24
  match_test_to_ref: True
  reference_object:
    object: "GenVisTau"
    x_arg: "pt"
    label: "Gen Taus"
    cuts:
      event:
        # - "{dr_0.3} < 0.15"
        - "abs({eta}) < 1.5"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    L1Tau:default: "pt"
    L1Jet:default: "pt"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency (Barrel)"
  binning:
    min: 0
    max: 150
    step: 6

TausMatchingEndcap:
  sample: TT
  version: Run3Winter24
  match_test_to_ref: True
  reference_object:
    object: "GenVisTau"
    x_arg: "pt"
    label: "Gen Taus"
    cuts:
      event:
        # - "{dr_0.3} < 0.15"
        - "abs({eta}) > 1.5"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    L1Tau:default: "pt"
    L1Jet:default: "pt"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency (Endcap)"
  binning:
    min: 0
    max: 150
    step: 6

TausMatchingEndcap_2p1:
  sample: TT
  version: Run3Winter24
  match_test_to_ref: True
  reference_object:
    object: "GenVisTau"
    x_arg: "pt"
    label: "Gen Taus"
    cuts:
      event:
        # - "{dr_0.3} < 0.15"
        - "abs({eta}) > 1.5"
      object:
        - "abs({eta}) < 2.1"
  test_objects:
    L1Tau:default: "pt"
    L1Jet:default: "pt"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency (Endcap)"
  binning:
    min: 0
    max: 150
    step: 6
