TkMuonsTrigger_Barrel:
  sample: DYLL_M50
  version: V38nano_DT12x_DT12x
  match_test_to_ref: True
  reference_object:
    object: "GenPart"
    x_arg: "eta"
    label: "Gen Muons"
    cuts:
      event:
        - "(({statusFlags}>>7)&1) == 1"
        - "abs({pdgId}) == 13"
      object:
        - "abs({eta}) < 0.83"
  test_objects:
    # L1gmtMuon:default:barrel: "pt"
    # L1gmtTkMuon:default:barrel: "pt"
    L1gmtTkMuon:VLoose:barrel: "pt"
    L1gmtTkMuon:Loose:barrel: "pt"
    L1gmtTkMuon:Medium:barrel: "pt"
    L1gmtTkMuon:Tight:barrel: "pt"
  xlabel: "Gen. pT (GeV)"
  ylabel: "Trigger Efficiency (barrel, L1 $p_T > 20$ GeV)"
  thresholds: [20, 25]
  scalings:
    method: "naive"
    threshold: 0.95
  binning:
    min: 0
    max: 50
    step: 1.5

TkMuonsTrigger_Overlap:
  sample: DYLL_M50
  version: V38nano_DT12x_DT12x
  match_test_to_ref: True
  reference_object:
    object: "GenPart"
    x_arg: "eta"
    label: "Gen Muons"
    cuts:
      event:
        - "(({statusFlags}>>7)&1) == 1"
        - "abs({pdgId}) == 13"
      object:
        - "abs({eta}) > 0.83"
        - "abs({eta}) < 1.24"
  test_objects:
    # L1gmtMuon:default:overlap: "pt"
    # L1gmtTkMuon:default:overlap: "pt"
    L1gmtTkMuon:VLoose:overlap: "pt"
    L1gmtTkMuon:Loose:overlap: "pt"
    L1gmtTkMuon:Medium:overlap: "pt"
    L1gmtTkMuon:Tight:overlap: "pt"
  xlabel: "Gen. pT (GeV)"
  ylabel: "Trigger Efficiency (overlap, L1 $p_T > 20$ GeV)"
  thresholds: [20, 25]
  scalings:
    method: "naive"
    threshold: 0.95
  binning:
    min: 0
    max: 50
    step: 1.5

TkMuonsTrigger_Endcap:
  sample: DYLL_M50
  version: V38nano_DT12x_DT12x
  match_test_to_ref: True
  reference_object:
    object: "GenPart"
    x_arg: "eta"
    label: "Gen Muons"
    cuts:
      event:
        - "(({statusFlags}>>7)&1) == 1"
        - "abs({pdgId}) == 13"
      object:
        - "abs({eta}) > 1.24"
  test_objects:
    # L1gmtMuon:default:endcap: "pt"
    # L1gmtTkMuon:default:endcap: "pt"
    L1gmtTkMuon:VLoose:endcap: "pt"
    L1gmtTkMuon:Loose:endcap: "pt"
    L1gmtTkMuon:Medium:endcap: "pt"
    L1gmtTkMuon:Tight:endcap: "pt"
  xlabel: "Gen. pT (GeV)"
  ylabel: "Trigger Efficiency (endcap, L1 $p_T > 20$ GeV)"
  thresholds: [20, 25]
  scalings:
    method: "naive"
    threshold: 0.95
  binning:
    min: 0
    max: 50
    step: 1.5
