GenMET:
  label: "GenMET"
  eta_ranges:
    inclusive: [0, 7]

L1Jet:
  match_dR: 0.3
  label: "Calo Jet"
  eta_ranges:
    inclusive: [0, 7]
    barrel: [0, 1.5]
    endcap: [1.5, 2.4]
    forward: [2.4, 5]
  cuts:
    inclusive:
      - "abs({eta}) < 7"
  ids:
    default:
      cuts:
        inclusive:
          - "abs({eta}) < 7"

L1EtSum:
  match_dR: 0.3
  label: "L1 EtSum"
  eta_ranges:
    inclusive: [0, 7]
  # cuts:
  #   inclusive:
  #     - "abs({eta}) < 7"
  ids:
    MET:
      label: "MET"
      cuts:
        inclusive:
          - "{etSumType} == 1"
    METHF:
      label: "MET"
      cuts:
        inclusive:
          - "{etSumType} == 8"
    HT:
      label: "MET"
      cuts:
        inclusive:
          - "{etSumType} == 1"