L1Tau:
  label: "Calo Tau"
  match_dR: 0.3
  eta_ranges:
    inclusive: [0, 7]
    barrel: [0, 1.5]
    endcap: [1.5, 2.4]
  ids:
    default:
      cuts:
        inclusive:
          - "abs({eta}) < 2.4"
