"""Write seeds as a CMSSW P2GT menu cff in the structured form.

Conditions reference the shared object definitions of the menu
(`object = gt_ref("...")`) and use offline thresholds, see
L1Trigger/Phase2L1GT/README.md ("Structured menus") in CMSSW.
"""

from menu_tools.menu_translation.object_mapping import ObjectMapping
from menu_tools.menu_translation.seed_model import (
    Leg,
    Seed,
    TranslationError,
    seed_name_to_cmssw,
    seed_name_to_cmssw_path,
)

CONDITIONS = {
    1: "l1tGTSingleObjectCond",
    2: "l1tGTDoubleObjectCond",
    3: "l1tGTTripleObjectCond",
    4: "l1tGTQuadObjectCond",
}

HEADER = """import FWCore.ParameterSet.Config as cms

############################################################
# Generated by menu_tools.menu_translation from {source}
############################################################

from L1Trigger.Phase2L1GT.l1tGTSingleObjectCond_cfi import l1tGTSingleObjectCond
from L1Trigger.Phase2L1GT.l1tGTDoubleObjectCond_cfi import l1tGTDoubleObjectCond
from L1Trigger.Phase2L1GT.l1tGTTripleObjectCond_cfi import l1tGTTripleObjectCond
from L1Trigger.Phase2L1GT.l1tGTQuadObjectCond_cfi import l1tGTQuadObjectCond

from L1Trigger.Phase2L1GT.l1tGTAlgoBlockProducer_cff import algorithms

from {menu_package}.l1tGTObject_constants import *
from {menu_package}.l1tGTMenuObjects_cff import *
"""

DEFAULT_MENU_PACKAGE = (
    "L1Trigger.Configuration.Phase2GTMenus.SeedDefinitions.step1_2024"
)


def _num(value: float) -> str:
    return repr(float(value))


def _leg_parameters(leg: Leg, mapping: ObjectMapping) -> list[str]:
    obj = mapping.to_cmssw(leg.object)
    params = [f'object = gt_ref("{obj.object}")']
    if obj.ptScaling:
        params.append(f'ptScaling = gt_ref("{obj.ptScaling}")')
    if leg.threshold is not None:
        variable = "ScalarSumPt" if obj.threshold == "scalarSumPt" else "Pt"
        prefix = "offlineMin" if leg.threshold.offline else "min"
        params.append(f"{prefix}{variable} = cms.double({_num(leg.threshold.value)})")
    if leg.abs_eta_max is not None:
        params.append(f"minEta = cms.double({_num(-leg.abs_eta_max)})")
        params.append(f"maxEta = cms.double({_num(leg.abs_eta_max)})")
    if leg.pv_dz_max is not None:
        params.append(f"maxPrimVertDz = cms.double({_num(leg.pv_dz_max)})")
        params.append("primVertex = cms.uint32(0)")
    return params


def _correlation_parameters(cuts: dict) -> list[str]:
    params = []
    for cut, value in cuts.items():
        if cut in ("os", "ss"):
            if value:
                params.append(f"{cut} = cms.bool(True)")
        else:
            params.append(f"{cut} = cms.double({_num(value)})")
    return params


def _block(name: str, params: list[str], indent: str) -> list[str]:
    inner = indent + "    "
    return (
        [f"{indent}{name} = cms.PSet("]
        + [inner + p + "," for p in params]
        + [f"{indent}),"]
    )


def seed_to_cmssw(seed: Seed, mapping: ObjectMapping) -> str:
    n_legs = len(seed.legs)
    if n_legs not in CONDITIONS:
        raise TranslationError(f"{n_legs} legs, P2GT conditions support 1-4")
    module = seed_name_to_cmssw(seed.name)
    path = seed_name_to_cmssw_path(seed.name)
    indent = "    "
    lines = [f"{module} = {CONDITIONS[n_legs]}.clone("]
    if n_legs == 1:
        lines += [indent + p + "," for p in _leg_parameters(seed.legs[0], mapping)]
    else:
        for k, leg in enumerate(seed.legs, start=1):
            lines += _block(f"collection{k}", _leg_parameters(leg, mapping), indent)
    for (i, j), cuts in sorted(seed.correlations.items()):
        params = _correlation_parameters(cuts)
        if n_legs == 2:
            lines += [indent + p + "," for p in params]
        elif params:
            lines += _block(f"correl{i}{j}", params, indent)
    lines.append(")")
    lines.append(f"{path} = cms.Path({module})")
    lines.append(f'algorithms.append(cms.PSet(expression = cms.string("{path}")))')
    return "\n".join(lines) + "\n"


def write_cmssw_menu(
    seeds: list[Seed],
    mapping: ObjectMapping,
    source: str = "",
    menu_package: str = DEFAULT_MENU_PACKAGE,
) -> tuple[str, dict[str, str]]:
    """(cff text, {skipped seed: reason})"""
    blocks = [HEADER.format(source=source, menu_package=menu_package)]
    skipped = {}
    for seed in seeds:
        try:
            blocks.append(seed_to_cmssw(seed, mapping))
        except TranslationError as e:
            skipped[seed.name] = str(e)
    return "\n".join(blocks), skipped
