L1puppiMET:
  label: "Puppi MET"
  ids:
    default: {}

L1puppiMLMET:
  label: "Puppi MLMET"
  ids:
    default: {}

L1puppiJetSC4sums:
  ids:
    HT:
      label: "SeededCone HT"
      cuts:
        inclusive:
          - "{sumType} == 0"
    MHT:
      label: "SeededCone MHT"
      cuts:
        inclusive:
          - "{sumType} == 1"

L1puppiHistoJetSums:
  ids:
    HT:
      label: "Histogrammed Puppi HT"
      cuts:
        inclusive:
          - "{sumType} == 0"
    MHT:
      label: "Histogrammed Puppi MHT"
      cuts:
        inclusive:
          - "{sumType} == 1"
