HT_90perc:
  sample: TT
  version: V32
  reference_object:
    object: "GenJet"
    x_arg: "pt"
    label: "Gen HT"
    trafo: "HT"
    cuts:
       object:
         - "abs({eta}) < 2.4"
         - "{pt} > 30"
  test_objects:
    trackerHT:default: ""
    phase1PuppiHT:default: ""
    seededConePuppiHT:default: ""
  thresholds: [350]
  scalings:
    method: "naive"
    threshold: 0.90
  xlabel: "Gen. HT (GeV)"
  ylabel: "Trigger Efficiency (<threshold> GeV)"
  binning:
    min: 0
    max: 750
    step: 20

# HT_50perc:
#   sample: TT
#   version: V32
#   reference_object:
#     object: "GenJet"
#     x_arg: "pt"
#     label: "Gen HT"
#     trafo: "HT"
#     cuts:
#        object:
#          - "abs({eta}) < 2.4"
#          - "{pt} > 30"
#   test_objects:
#     # trackerHT:default: ""
#     # phase1PuppiHT:default: ""
#     seededConePuppiHT:default: ""
#   thresholds: [350]
#   scalings:
#     method: "naive"
#     threshold: 0.50
#   xlabel: "Gen. HT (GeV)"
#   ylabel: "Trigger Efficiency (<threshold> GeV)"
#   binning:
#     min: 0
#     max: 750
#     step: 20

MHT_50perc:
  sample: TT
  version: V32
  reference_object:
    object: "GenJet"
    x_arg: "pt"
    label: "Gen MHT"
    cuts:
      object:
        - "abs({eta}) < 2.4"
        - "{pt} > 30"
    trafo: "MHT"
  test_objects:
    trackerMHT:default: ""
    phase1PuppiMHT:default: "et"
    seededConePuppiMHT:default: "et"
  thresholds: [70, 150]
  scalings:
    method: "naive"
    threshold: 0.50
  xlabel: "Gen. MHT30 (GeV)"
  ylabel: "Trigger Efficiency (<threshold> GeV)"
  binning:
    min: 0
    max: 500
    step: 20

# MHT_90perc:
#   sample: TT
#   version: V32
#   reference_object:
#     object: "GenJet"
#     x_arg: "pt"
#     label: "Gen MHT"
#     cuts:
#       object:
#         - "abs({eta}) < 2.4"
#         - "{pt} > 30"
#     trafo: "MHT"
#   test_objects:
#     # trackerMHT:default: ""
#     # phase1PuppiMHT:default: "et"
#     seededConePuppiMHT:default: "et"
#   thresholds: [70, 150]
#   scalings:
#     method: "naive"
#     threshold: 0.90
#   xlabel: "Gen. MHT30 (GeV)"
#   ylabel: "Trigger Efficiency (<threshold> GeV)"
#   binning:
#     min: 0
#     max: 500
#     step: 20

# MET_90perc:
#   sample: TT
#   version: V32
#   reference_object:
#     object: "genMetTrue"
#     x_arg: ""
#     label: "Gen MET"
#   test_objects:
#     trackerMET:default: ""
#     puppiMET:default: "et"
#   thresholds: [150]
#   xlabel: "Gen. MET (GeV)"
#   ylabel: "Trigger Efficiency (<threshold> GeV)"
#   scalings:
#     method: "naive"
#     threshold: 0.90
#   binning:
#     min: 0
#     max: 500
#     step: 20

# MET_50perc:
#   sample: TT
#   version: V32
#   reference_object:
#     object: "genMetTrue"
#     x_arg: ""
#     label: "Gen MET"
#   test_objects:
#     # trackerMET:default: ""
#     puppiMET:default: "et"
#   thresholds: [150]
#   xlabel: "Gen. MET (GeV)"
#   ylabel: "Trigger Efficiency (<threshold> GeV)"
#   scalings:
#     method: "naive"
#     threshold: 0.50
#   binning:
#     min: 0
#     max: 500
#     step: 20
