L1tkPhoton:
  match_dR: 0.15
  eta_ranges:
    inclusive: [0, 5]
    barrel: [0, 1.479]
    endcap: [1.479, 2.4]
  ids:
    NoIso:
      label: "L1tkPhoton"
      cuts:
        inclusive:
          - "abs({eta}) < 2.4"
          - "{pt} > 5"
        barrel:
          - "{eleId} == 1"
        endcap:
          - "{phoId} == 1"
    Iso:
      label: "L1tkIsoPhoton"
      cuts:
        inclusive:
          - "abs({eta}) < 2.4"
          - "{pt} > 5"
        barrel:
          - "abs({relIso}) < 0.25"
          - "{eleId} == 1"
        endcap:
          - "abs({relIso}) < 0.205"
          - "{phoId} == 1"
