name: Python Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install flake8 flake8-bugbear pytest
          if [ -f objectPerformance/requirements.txt ]; then pip install -r objectPerformance/requirements.txt; fi
      - name: Run Flake8
        run: flake8 objectPerformance
      - name: Run Tests
        run: |
          cd objectPerformance
          python -m pytest

